### ISSUE TITLE
"Error: Invalid filename" on filepath with spaces or special characters

### ISSUE THREAD

**Issue by giovannisaraceno** [avirillion/vscode-taskfalcon#1]
Hi,
the extension is great until the path of the main file has spaces or special chars.

In that case the output console emits an "Error: Invalid filename".

Maybe a some kind of sanitization (embrace path with double quotes?) of filepath is needed when the extension launch the taskfalcon cli command.

**Comment by avirillion** [comment]
Thank you for raising this bug.

I just published a bugfix to properly escape parameters to taskfalcon.

Cheers,
Marc
